# Generated by Django 3.2 on 2021-05-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('sn', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('timestamps', models.DateTimeField(blank=True)),
            ],
        ),
    ]
