# Generated by Django 3.2 on 2021-05-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sn', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=225)),
                ('phone', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=70)),
                ('content', models.TextField()),
            ],
        ),
    ]
